
<template>
    <div class="content">
        <h1>
            404. Page Not Found
        </h1>
        <p>Copied content could not find it way to the Database adviced to retarce steps</p>
    </div>
</template>

<script>
export default {
    name: 'PageNotFound'
}
</script>


<style>
#app.content {
    margin-right: auto;
    margin-left: auto;
    /* top: auto; */
    margin: 1px solid #000000;
    width: 300px;
    height: auto;
    background-color: #1F8F76;
}
</style>
